# -*- coding: utf-8 -*-
"""Titanic-Elevvo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8TxkcIwvMZvrK9mBlL8mPVPAfZbLZo3
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Plot style
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10,6)

# If you see train.csv in the Colab "Files" sidebar, it is in /content/
df = pd.read_csv("/content/train.csv")

print("Shape of dataset:", df.shape)
df.head()

# Convert to categorical
df['Pclass'] = df['Pclass'].astype('category')
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')

# Fill missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Fare'] = df['Fare'].fillna(df['Fare'].median())

print("\nMissing values after cleaning:\n", df.isnull().sum())

# Family size & Alone flag
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)

# Extract Title
df['Title'] = df['Name'].str.extract(r',\s*([^\.]+)\.', expand=False)
df['Title'] = df['Title'].replace(['Mlle','Ms'],'Miss').replace('Mme','Mrs')
rare_titles = df['Title'].value_counts()[df['Title'].value_counts() < 10].index
df['Title'] = df['Title'].replace(rare_titles, 'Rare')
df['Title'] = df['Title'].astype('category')

# Age groups
bins = [0, 12, 20, 40, 60, 120]
labels = ['Child','Teen','Adult','MidAge','Senior']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)

df[['PassengerId','Name','Title','Age','AgeGroup','FamilySize','IsAlone']].head()

overall_survival = df['Survived'].mean()
print(f"\nOverall survival rate: {overall_survival:.2%}")

print("\nSurvival by Sex:")
print(df.groupby('Sex')['Survived'].mean())

print("\nSurvival by Pclass:")
print(df.groupby('Pclass')['Survived'].mean())

print("\nSurvival by AgeGroup:")
print(df.groupby('AgeGroup')['Survived'].mean())

print("\nSurvival by Title:")
print(df.groupby('Title')['Survived'].mean())

# 1. Survival count
sns.countplot(x='Survived', data=df)
plt.title("Overall Survival Count (0 = No, 1 = Yes)")
plt.show()

# 2. Survival by gender
sns.barplot(x='Sex', y='Survived', data=df)
plt.title("Survival Rate by Gender")
plt.show()

# 3. Survival by class
sns.barplot(x='Pclass', y='Survived', data=df)
plt.title("Survival Rate by Passenger Class")
plt.show()

# 4. Age distribution by survival
sns.kdeplot(data=df[df['Survived']==1], x="Age", label="Survived", fill=True)
sns.kdeplot(data=df[df['Survived']==0], x="Age", label="Not Survived", fill=True)
plt.title("Age Distribution: Survived vs Not Survived")
plt.legend()
plt.show()

# Correlation heatmap
corr = df[['Survived','Age','SibSp','Parch','Fare','FamilySize','IsAlone']].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# Survival by Sex & Pclass
pivot_sex_pclass = pd.pivot_table(df, index='Sex', columns='Pclass',
                                  values='Survived', aggfunc='mean')
sns.heatmap(pivot_sex_pclass, annot=True, fmt=".2f", cmap="YlGnBu")
plt.title("Survival Rate: Sex vs Pclass")
plt.show()

# Save cleaned CSV to /content
clean_path = '/content/titanic_cleaned.csv'
df.to_csv(clean_path, index=False)
print(f"Saved cleaned CSV to: {clean_path}")

# If you want to save to your Google Drive (optional)
# from google.colab import drive
# drive.mount('/content/drive')
# df.to_csv('/content/drive/MyDrive/titanic_cleaned.csv', index=False)

print("\nKey Insights:")
print("- Females had higher survival rates than males.")
print("- 1st class passengers had higher survival rates than 2nd and 3rd.")
print("- Children generally had higher survival rates than adults.")
print("- Titles (Mrs, Miss) show different survival patterns.")
print("- Family size and being alone also affected survival.")